name: Build iOS
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Theos
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          git clone --recursive https://github.com/theos/theos.git ~/theos
      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: HARA_IOS_DYLIB
          path: packages/*.deb
